data/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url
from data import views

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'file', views.FileViewSet)
router.register(r'data', views.DataViewSet)
router.register(r'project', views.ProjectViewSet)
urlpatterns = patterns('',
    )

urlpatterns += router.urls

mightyscreen/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView


from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$',TemplateView.as_view(template_name="index.html"),name='index'),
    url(r'^upload/',TemplateView.as_view(template_name="upload.html"),name='uploadview'),
    url(r'^table/',TemplateView.as_view(template_name="tableview.html"),name='tableview'),
    url(r'^plate/',TemplateView.as_view(template_name="plateview.html"),name='plateview'),
    url(r'^admin/', include(admin.site.urls)),
    #url(r'^api/', include('library.urls')),
    url(r'^api/', include('data.urls')),
    url(r'^accounts/', include('accounts.urls')),
)

data/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.files.storage import FileSystemStorage
from django.conf import settings
from rest_framework import serializers
from django.core.serializers.json import DjangoJSONEncoder
import uuid, os
import json
from django.shortcuts import get_object_or_404
from collections import OrderedDict as odict
from django.db.models import Sum,Max
import datetime
#Create your models here.

class JSONField(models.TextField):
    """
    JSONField is a generic textfield that neatly serializes/unserializes
    JSON objects seamlessly.
    Django snippet #1478

    example:
        class Page(models.Model):
            data = JSONField(blank=True, null=True)


        page = Page.objects.get(pk=5)
        page.data = {'title': 'test', 'type': 3}
        page.save()
    """

    __metaclass__ = models.SubfieldBase

    def to_python(self, value):
        if value == "":
            return None
        try:
            if isinstance(value, basestring):
                return json.loads(value,object_pairs_hook=odict)
        except ValueError:
            pass
        return value

    def get_db_prep_save(self, value, *args, **kwargs):
        if value == "":
            return None
        if isinstance(value, dict):
            value = json.dumps(value, cls=DjangoJSONEncoder)
        return super(JSONField, self).get_db_prep_save(value, *args, **kwargs)


class project(models.Model):

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    name = models.CharField(max_length=20,verbose_name='Project Name',default='Untitled')

    memo = models.TextField(blank=True)

    user = models.ForeignKey(User,null=True,blank=True)

    meta = JSONField(blank=True,null=True)#this stores a dictionary of the meta data of this project.

    create_date = models.DateTimeField(auto_now_add=True, blank=True)

    def get_plate_list(self):
        """
        return a list of plates ######need to improve.
        """

        return self.data_set.order_by('plate').distinct().values_list('plate',flat=True)

    def get_detail_plate_list(self):
        """
        return a detailed list of plates
        """
        return self.data_set.values('plate').order_by('plate').annotate(numHit=Sum('hit'),date=Max('create_date'))

    def get_meta(self):#meta is a dictionary/json but I didn't enforce that. could be improved.
        if self.meta == None:
            return dict()
        else:
            return self.meta

    def get_curPlate(self,request=None):
        """
        A function to get current plate number
        """

        self.meta = self.get_meta()

        curPlate = self.meta['curPlate'] if 'curPlate' in self.meta.keys() else None
        
        if request != None:
            curPlate = request.GET.get('plate',curPlate)

        if  not self.data_set.filter(plate=curPlate).exists():

            curPlate = self.get_plate_list()[0] if len(self.get_plate_list()) > 0 else None

        self.meta['curPlate'] = curPlate

        self.save()

        return curPlate


class ProjectSerializer(serializers.ModelSerializer):

    class Meta:
        model = project
        fields = 'id name memo meta user create_date'.split()
        read_only_fields = 'id meta'.split()

# def get_curPlate(request):

#     p = get_object_or_404(project,id=request.session.get('project',None))

#     pdata = data.objects.filter(project=p)

#     plate_list = [ i['plate'] for i in pdata.order_by('plate').values('plate').distinct()]

#     #check request
#     plate = request.GET.get('plate',
#         request.session.get('plate',
#                 plate_list[0] if plate_list != [] else None
#             )
#         )

#     print plate
#     #set the plate number in session
#     request.session['plate'] = plate

#     return plate


def create_project(request):
    if request.user.is_anonymous():

        p = project(user=None) #anonymouse user cannot be saved as a user object

    else:

        projs_names = project.objects.filter(user=request.user).values_list('name',flat=True)

        #figure out the numbering
        number = 0
        for i in projs_names:
            try:
                number = int(i.split('Untitled')[1]) if int(i.split('Untitled')[1]) >  number else number
            except:
                pass

        p = project(name= 'Untitled ' + str(number+1),user=request.user)

    p.save()
    
    return p


def get_or_create_project(request):
    """
    find the project instance based on request
    if can't find any, create one and return the new project
    """



    if request.user.is_anonymous():

        if project.objects.filter(id=request.session.get('project', None)).exists():
        
            p = project.objects.get(id=request.session.get('project', None))
        
        else:

            p = create_project(request)
    else:

        if project.objects.filter(id=request.session.get('project', None),user=request.user).exists(): #if can project

            p = project.objects.get(id=request.session.get('project', None),user=request.user)

        elif project.objects.filter(user=request.user).exists():
            
            p = project.objects.filter(user=request.user)[0]

            request.session['project'] = p.id.hex
        
        else:

            p = create_project(request)


    request.session['project'] =  p.id.hex #set the session project keyword
    request.session['project_name'] =  p.name
    
    return p





def get_file_name(instance,filename):
	"""
	This convert a filename to a unique filename
	"""
	return os.path.join(settings.CSV_FILE_DIR,uuid.uuid4().hex+'.csv')



class csv_file(models.Model):
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    create_date = models.DateTimeField(auto_now_add = True, blank = True)

    project = models.ForeignKey('project',null=True,blank=True)

    raw_csv_file = models.FileField(null=True,upload_to=get_file_name)


#Serializer for REST framework


class csv_file_serializer(serializers.ModelSerializer):

    
    class Meta:
        model = csv_file
        fields = 'id project raw_csv_file'.split()
        read_only_fields = 'id project'.split()
        write_only_fields = 'raw_csv_file'.split()

# Receive the pre_delete signal and delete the file associated with the model instance.
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver

@receiver(pre_delete, sender=csv_file)
def csv_file_delete(sender, instance, **kwargs):
	"""
	make sure when csv_file model is deleted the files get deleted too.
	"""
	# Pass false so FileField doesn't save the model.
	instance.raw_csv_file.delete(False)



#Data object
#Two ways of identify compound. FaciclityID? or Plate+Well
#Pubchem is used to identify compound
class data(models.Model):
    
    def __unicode__(self):
    
        return self.project.name+self.plate_well
        
    class Meta:

        unique_together = ('plate_well','project')
        index_together = ['plate_well','project']
    
    identifier = models.TextField()

    plate_well = models.CharField(max_length=50)#using plate well as unique identifier, not good for more than one libraries

    plate = models.IntegerField()

    well = models.CharField(max_length=20)
    
    hit=models.PositiveSmallIntegerField(default=0,verbose_name='Hit')

    schoice = (
    ('B','bad well'),
    ('E','empty'),
    ('P','positive control'),
    ('N','negative control'),
    ('X','compound'),
    )
    
    welltype=models.CharField(max_length=1,choices=schoice,default='X')

    project = models.ForeignKey(project)
    
    create_date = models.DateTimeField(auto_now_add = True, blank = True)

    readouts = JSONField(blank=True,null=True)

    
#the serializer for data
class DataSerializer(serializers.ModelSerializer):
    create_date = serializers.DateTimeField(format='%Y-%m-%d %H:%M')

    class Meta:
        model = data
        fields = 'plate_well plate well identifier hit welltype create_date'.split()

    def to_representation(self,obj):#just to add readouts to it.
        data = super(DataSerializer,self).to_representation(obj)
        readouts = obj.readouts
        if (type(readouts) is odict):
            data.update(readouts)
        
        return  data

templates/base.html
{# This is the base template for all web pages #}
{% load staticfiles %}


<!doctype html>
<html>


<head>
    <meta charset="UTF-8">
    <title>MightyScreen</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet" type="text/css">
    <link href="{% static "main.css" %}" rel="stylesheet" type="text/css">
    
    {% block css %}

    {% endblock %}

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>

<body style="padding-top:65px;padding-bottom:50px;">
    <!-- Top Navigation Bar -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="wrapper">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'index' %}">MightyScreen</a>
            </div>

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li {% if request.resolver_match.url_name == 'uploadview' %}class="active"{% endif %}><a href="{% url "uploadview" %}">Upload</a></li>
                    <li {% if request.resolver_match.url_name == 'tableview' %}class="active"{% endif %}><a href="{% url "tableview" %}">TableView</a></li>
                    <li {% if request.resolver_match.url_name == 'plateview' %}class="active"{% endif %}><a href="{% url "plateview" %}">PlateView</a></li>
                    {% if user.is_authenticated %}
                    <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                    Proj:{% if request.session.project %}<span id="curProjectName" class="badge">{{request.session.project_name}}</span>{% endif %}
                    <span class="caret"></span>
                    </a>
                        <ul class="dropdown-menu">
                            {% for project in user.project_set.all %}
                                {% if request.session.project != project.id.hex %}
                                    <li><a href="{% url 'project-list' %}{{ project.id }}/use">{{ project.name|title }}</a></li>
                                {% endif %}
                            {% endfor %}
                            <li class="divider"></li>
                            <li><a href="{% url 'project-new' %}">New Project</a></li>
                            <li><a href="#" onclick="change_proj_name('{{request.session.project}}','{{request.session.project_name}}');">Rename Project</a></li>
                            <li><a href="#" onclick="delete_proj('{{request.session.project}}','{{request.session.project_name}}');">Delete Project</a></li>
                            
                        </ul>
                    </li>
                    {% else %}
                    <li><a href="{% url "project-new" %}" onclick="return confirm('All data will be lost. Are you sure?')">ClearData</a></li>
                    {% endif %}

                    <li><a href="{% url 'data-to-csv' %}">ExportData</a></li>
                    <li><a href="http://longfei-wang.github.io/mightyscreen/" target="_top">Help</a></li>

                </ul>

                {% if user.is_authenticated %}
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <span class="glyphicon glyphicon-user"></span>
                         <span class="caret"></span>
                        </a>
                            <ul class="dropdown-menu">
                                <li><a href="{% url "profile" %}">Profile</a></li>
                                <li class="divider"></li>
                                <li><a href="{% url "logout" %}">Logout</a></li>
                            </ul>
                        </li>
                    </ul>

                    <p class="navbar-text navbar-right">
                        Welcome, {{user.username}}
                    </p>


                {% else %}

                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="{% url "login" %}?next={{request.path}}"><span class="glyphicon glyphicon-user"></span>&nbsp;&nbsp;&nbsp;&nbsp;</a></li>
                    </ul>
                {% endif %}
            </div><!--/.navbar-collapse -->
        </div>
    </nav>


<!-- row of columns -->
<div class="wrapper container-fluid">

    <div class="row">

        <div class="col-lg-12 col-md-12 col-sm-12">
                {# all messages will be displayed here #}
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{% if message.tags in 'error debug'  %}danger{% else %}{{message.tags}}{% endif %}">{{message|safe}}
                            <a class="close" data-dismiss="alert" href="#" aria-hidden="true">&times;</a>
                        </div>
                    {% endfor %}
                {% endif %}
                
                <div id="nodata" class="hide"> 
                    <div class="alert alert-danger">
                    There is no data in your current project. Do you want to <a href="{% url 'data-demo' %}">Load Demo</a>?
                    <a class="close" data-dismiss="alert" href="#" aria-hidden="true">&times;</a>
                    </div>
                </div>

                <div id="contentblock">
                {% block content %}
                
                {% endblock %}
                </div>
        </div>

    </div>


    <hr>
    <div class="row container">
        <footer>
            <p>
            Copyright © MightyScreen 2013 ||
            <a href='https://github.com/longfei-wang/mightyscreen'>SourceCode</a>
            </p>
        </footer>
    </div>
</div> <!-- /container -->

<script src="{% static "js/jquery.min.js" %}"></script>
<script src="{% static "js/bootstrap.min.js" %}"></script>
<script src="{% static "js/d3.min.js" %}"></script>
<script src="{% static "js/bootbox.min.js" %}"></script>

<script>
var change_proj_name = function(pk,name) {
    bootbox.prompt({
        title: "Please input the new name for current project",
        value: name?name:'',
        callback: function(result) {                
            if (result === null) {                                             
                                              
            } else {
                $.get('{% url "project-list" %}'+pk+'/rename/',{name:result},function(d) {
                    if (d.name) {
                        location.reload();
                    }
                });                          
            }
        }
    });
}

var delete_proj = function(pk,name) {
    bootbox.confirm("All data in project "+name+" will be lost. Are you sure?", function(result) {
    if (result) {
        $.get('{% url "project-list" %}'+pk+'/delete/',{},function(d){
            if (d.results) {
                location.reload();
            }
        });
    }
});

}

// var confirm_action = function(message,url) {
//     bootbox.confirm(message, function(result) {
//     if (result) {

//     }
// }); 
// }
</script>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-66598191-1', 'auto');
  ga('send', 'pageview');

</script>

{% block script %}

{% endblock %}

</body>
</html>

templates/documents.html
{% extends 'main/base.html' %}
{% load fiber_tags %}
{% block content %}
{% show_page_content "overview" %}
{% endblock %}

templates/error.html
{% extends 'base.html' %}

{% block content %}

<div class="alert alert-danger"><strong>
Unfortuntely, we have an error: "{{ error_msg }}"
</strong></div>

{% endblock %}

templates/index.html
{% extends 'base.html' %}


{% block content %}

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1>Welcome to MightyScreen!</h1>
        <p>A simple but comprehensive data analysis tool for high-throughput screens.</p>
        <p><a href="{% url 'uploadview' %}" class="btn btn-primary btn-lg" role="button">Get Start &raquo;</a></p>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Visualization</h2>
          <p>MightyScreen encodes massive data into various visual elements which enable users to gain a comprehensive understanding of their data.</p>
       </div>
        <div class="col-md-4">
          <h2>Better Hit Selection</h2>
          <p>MightyScreen facilitates the superior pattern recognition and decision making ability of human with its interactive visualization design.</p>
        </div>
        <div class="col-md-4">
          <h2>No limitation</h2>
          <p>MightyScreen supports an unlimited number of numeric measurements/readouts.</p>
        </div>
      </div>
    </div>

{% endblock %}

templates/plateview.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block css %}

<!-- add own stylesheet-->
<link rel="stylesheet" type="text/css" href="{% static 'myStyle.css' %}">

{% endblock %}

{% block content %}

<div id="visualization">
        <div class="row">
            <div class="col-md-12 col-sm-12" id="plateSelector">
            </div>

        </div>

    <hr>
        <div class="row">
            <div class="col-md-12" id="chemicalVis"></div>
        </div>
    <hr>
        <div class="row">
            <div class = "col-lg-6 col-md-12">

            <div class="col-md-12 row" id="dropdowns">
            </div>


            <div class="col-md-12" id="distVis1">
            </div>

            <div class="col-md-12" id="distVis2">
            </div>      

            <div class="col-md-12" id="distVis3">
            </div>    

            </div>
            <div class = "col-md-12 col-lg-6" id="plateVis">

            </div>

        </div>

<hr>
        <div class="row">
            <div class="col-lg-6 col-md-12" id="scatterVis1">
            </div>          
            <div class="col-lg-6 col-md-12" id="scatterVis2">
            </div>
        </div>

</div>

    <br>
    <br>
    <br>
    <br>
    <br>

{% endblock %}

{% block script %}
<script src="http://d3js.org/queue.v1.min.js"></script>
<script src = '{% static "plate_selector.js"%}'></script>
<script src = '{% static "dist.js"%}'></script>
<script src = '{% static "plate.js"%}'></script>
<script src = '{% static "scatter.js"%}'></script>
<script src = '{% static "chemical.js"%}'></script>



<script>
$(function(){ // this function is called after the HTML document is fully loaded


    //==========================================
    //--- HERE IS WHERE ALL THE MAGIC STARTS --
    //==========================================
    var url = "{% url 'data-list' %}";
    var markUrl = "{% url 'data-list' %}";
    // variables keeping global knowledge of the data
    var thisData = [];
    //brushed region
    var brush = {};
    // this function can convert Date objects to a string
    // it can also convert strings to Date objects
    // see: https://github.com/mbostock/d3/wiki/Time-Formatting
    var dateFormatter = d3.time.format("%Y-%m-%d");


    var wrangleData = function(_data) {
        
        thisData = _data;

        // thisData.results = _data.results.map(function (d) {
        
        //     var res = {
        //         platewell: d.plate_well,
        //         plate:d.plate,
        //         well:d.well,
        //         welltype:d.welltype,
        //     };

        //     thisData.channels.map(function(c,i){
        //         res[c] = parseFloat(d["readout"+(i+1)]);
        //     });

        //     // clean up svg make it symbol and set the id to be 'sym'+platewell suppose to be unique
        //     //res.svg = d.svg ? "<symbol id='sym" + d.platewell + "'" + d.svg.split("<svg")[2].split("</svg>")[0]+"</symbol>" : "";

        //     return res;
        // });
    }

    // call this function after Data is loaded, reformatted and bound to the variables
    var initVis = function(){

        //if there is not data display the nodata warning and return
        if (thisData.results.length < 1) {
            d3.select("#nodata").attr('class','');
            d3.select("#visualization").attr('class','hide');
            return;
        }

        //TODO: Create an eventHandler  --> DONE :)
        var MyEventHandler = new Object();

        //TODO: Instantiate all Vis Objects here

        //TODO: channel selector
        var dropdowns = d3.select("#dropdowns")
            .selectAll("select")
            .data([1,2,3])
            .enter()
            .append("div")
            .attr("class","col-md-3")
            .text(function(d){return "Channel "+d+": ";})
            .append("select")
            .attr("id",function(d) { return "select"+d;})
            .on("change",function(d) {
                $(MyEventHandler).trigger("channel",d);
        });

        dropdowns.selectAll("option")
            .data(thisData.channels)
            .enter()
            .append("option")
            .text(function(d) {return d;});


        //set the default
        d3.select("#select1").node().value = thisData.channels[0];
        d3.select("#select2").node().value = thisData.channels[1] ? thisData.channels[1] : thisData.channels[0];//if there is no more readouts just use readout 1
        d3.select("#select3").node().value = thisData.channels[2] ? thisData.channels[2] : thisData.channels[0];

        //select which plate to display
        var plateselector = new PlateSelector(d3.select("#plateSelector"),thisData,MyEventHandler);

        //channel 1 for selection
        var distvis1 = new DistVis(d3.select("#distVis1"),thisData,d3.select("#select1").node().value,MyEventHandler);
        
        //channel 2 for selection
        var distvis2 = new DistVis(d3.select("#distVis2"),thisData,d3.select("#select2").node().value,MyEventHandler);
        
        //channel 3 for selection
        var distvis3 = new DistVis(d3.select("#distVis3"),thisData,d3.select("#select3").node().value,MyEventHandler);

        //Chemical View 
        var chemicalvis = new ChemicalVis(d3.select("#chemicalVis"),thisData,MyEventHandler);

        //plate heat plot
        var platevis = new PlateVis(d3.select("#plateVis"),thisData,MyEventHandler)

        //scatter plot
        var scattervis1 = new ScatterVis(d3.select("#scatterVis1"),thisData,d3.select("#select1").node().value,d3.select("#select2").node().value,MyEventHandler);

        var scattervis2 = new ScatterVis(d3.select("#scatterVis2"),thisData,d3.select("#select1").node().value,d3.select("#select3").node().value,MyEventHandler);

        //chemical cloud
        //var cloudvis = new CloudVis(d3.select("#cloudVis"),groupedData[0].values,channel_1,1,MyEventHandler);




        // TODO: bind the eventHandler to the Vis Objects
        // events will be created from the CountVis object (nothing to do here)
        // events will be consumed by the PrioVis and AgeVis object (binding should happen here)
        $(MyEventHandler).bind("brush", function(event, s, e, c){
            
            brush[c] = [s,e];

            //update these visualization
            platevis.onSelectionChange(brush);
            scattervis1.onSelectionChange(brush);
            scattervis2.onSelectionChange(brush);
        });


        $(MyEventHandler).bind("plate", function(event, p){
            $.get(url,
                {'plate':p},
                function(d){
                    
                    wrangleData(d);

                    plateselector.onPlateChange(p);
                    distvis1.onPlateChange(thisData);
                    distvis2.onPlateChange(thisData);
                    distvis3.onPlateChange(thisData);
                    platevis.onPlateChange(thisData);
                    scattervis1.onPlateChange(thisData);
                    scattervis2.onPlateChange(thisData);
                    //cloudvis.onPlateChange(thisData);
                    chemicalvis.onPlateChange(thisData);

                });
        });

        $(MyEventHandler).bind("select", function(event, plate_well){
            
            //this is what happed after one select a compound
            $.get(markUrl+plate_well+"/mark/",
                {},
                function(d) {
                    //console.log(d);
                    chemicalvis.onChemSelectionChange(plate_well);
                    platevis.onChemSelectionChange(plate_well);
            });
            //update these visualization

        });

        $(MyEventHandler).bind("channel", function(event, c){

            var c1 = d3.select("#select1").node().value;
            var c2 = d3.select("#select2").node().value;
            var c3 = d3.select("#select3").node().value;

            distvis1.onChannelChange(c1);
            distvis2.onChannelChange(c2);
            distvis3.onChannelChange(c3);
            scattervis1.onChannelChange(c1,c2);
            scattervis2.onChannelChange(c1,c3);
            platevis.onChannelChange(c1);

        });
    }


    // call this function after both files are loaded -- error should be "null" if no error
    var dataLoaded = function (error, _data) {

        if (!error) {

            wrangleData(_data);
            
            //aggregate data based on plate number
            //console.log(thisData);
            initVis();
        }
    }



    var startHere = function(){

        //TODO: load data here and call "dataLoaded" afterwards
        // Hint: http://giscollective.org/d3-queue-js/
        queue()
        .defer(d3.json,url)
        .await(dataLoaded);


    }

    startHere();
})
</script>


{% endblock %}

templates/redirect.html
{% extends 'base.html' %}

{% block content %}

<META HTTP-EQUIV="Refresh" CONTENT="2; URL={% url dest %}"> 

<div class="alert alert-success"><strong>
{{message}}. We will redirect you to main page in a few seconds. If not, you can click 
<a href="{% url dest %}" class="alert-link">here.</a>
</strong>
</div>

{% endblock %}

templates/tableview.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block css %}


{% endblock %}



{% block content %}

<div id="visualization">

	<div class="row">
	    <div class="col-md-12 col-sm-12" id="plateSelector">
	    </div>

	</div>

	<div class="row well">
	    <div class="btn-group" role="group" aria-label="demo">
	        <a href="{% url 'data-layout' %}" class="btn btn-default">Appy current layout to other plates</a>
	    </div>
	</div>
	<div class="row">
		<div class="col-md-12 col-sm-12" id="tableview">
		</div>
	</div>

</div>

{% endblock %}


{% block script %}
<!-- <script src='{% static "util.js" %}'></script> -->
<script src='{% static "tablevis.js" %}'></script>
<script src = '{% static "plate_selector.js"%}'></script>
<script>
$(function() {

	var url = '{% url "data-list" %}';

	var MyEventHandler = new Object();

	var wrangleData = function(_data) {

		return _data;

	}

	// loading();

	d3.json(url,function(d){

		var thisData = wrangleData(d);
		
		//if there is not data display the nodata warning and return
        if (thisData.results.length < 1) {
            d3.select("#nodata").attr('class','');
            d3.select("#visualization").attr('class','hide');
        	return;
        }

		var tableview =new TableVis(d3.select("#tableview"),thisData,MyEventHandler);	
		
		var plateselector = new PlateSelector(d3.select("#plateSelector"),thisData,MyEventHandler);

        $(MyEventHandler).bind("hit", function(event, plate_well){

            d3.json(url+plate_well+'/mark',function(d){
            });
            //update these visualization

        });

        $(MyEventHandler).bind("welltype", function(event, plate_well, welltype){
            d3.json(url+plate_well+'/set'+welltype,function(d){
            });
            //update these visualization

        });

        $(MyEventHandler).bind("plate", function(event, p){

        	// loading();
            
            $.get(url,
                {'plate':p},
                function(d){
                    
                    plateselector.onPlateChange(p);
                    tableview.onPlateChange(wrangleData(d));
                    // loading_done();
                });
        });

        // loading_done();
	});

});


</script>

{% endblock %}